from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import Config

db = SQLAlchemy()

app = Flask(__name__)
app.config.from_object(Config)
db.init_app(app)

# Import and register Blueprints
from routes.public import public_bp
from routes.admin import admin_bp
from routes.payments import payments_bp
from routes.ndis import ndis_bp
from routes.driver import driver_bp

app.register_blueprint(public_bp)
app.register_blueprint(admin_bp, url_prefix='/admin')
app.register_blueprint(payments_bp, url_prefix='/payments')
app.register_blueprint(ndis_bp, url_prefix='/ndis')
app.register_blueprint(driver_bp, url_prefix='/driver')

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=8000)
